//! # Tenuto Execution & Delegation Protocol (TEDP) Daemon
//! 
//! `tenutod` acts as the master sequencer for the Tenuto 3.0 ecosystem.
//! It decouples the mathematical logic generated by `tenutoc` from the physical audio rendering,
//! orchestrating external DSP engines (SuperCollider, ChucK) via Open Sound Control (OSC)
//! and synchronizing with live performers via Ableton Link.

use std::sync::Arc;
use tokio::sync::Mutex;
use tokio::net::UdpSocket;
use rusty_link::Link;
use tenutoc::ir::Timeline;

mod osc_emitter;
mod link_sync;
mod scheduler;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🚀 Booting tenutod (Tenuto Execution & Delegation Protocol v3.0.1)");

    // 1. Initialize Ableton Link Phase Synchronization (TEDP 3.1)
    // The daemon decouples its internal logical tempo from the physical clock.
    let mut link = Link::new(120.0);
    link.enable(true);
    let link_state = Arc::new(Mutex::new(link));
    println!("🔗 Ableton Link Enabled. Awaiting peers...");

    // 2. Initialize OSC UDP Sockets (TEDP 2.0)
    // SuperDirt (TidalCycles) default port is 57120
    // ChucK default OSC port is typically 6449
    let superdirt_socket = Arc::new(UdpSocket::bind("0.0.0.0:0").await?);
    superdirt_socket.connect("127.0.0.1:57120").await?;
    
    let chuck_socket = Arc::new(UdpSocket::bind("0.0.0.0:0").await?);
    chuck_socket.connect("127.0.0.1:6449").await?;

    println!("📡 OSC Emitters Bound (SuperDirt: 57120, ChucK: 6449)");

    // 3. Load the Tenuto IR (Mocking a compiled timeline for the daemon loop)
    // In a real scenario, this would be fed via IPC or a file watcher from `tenutoc`.
    let dummy_timeline = Timeline {
        title: "Live Algorave Session".into(),
        tempo: 120,
        ppq: 1920,
        auto_pad_voices: true,
        swing: std::collections::HashMap::new(),
        humanize: 0.0,
        tracks: std::collections::HashMap::new(),
    };

    // 4. Start the Deterministic Look-Ahead Scheduler (TEDP 2.1)
    // The scheduler runs in a high-priority Tokio task, calculating the rational grid
    // against the Link phase and dispatching OSC bundles 200ms in advance.
    println!("⏱️ Starting Rational Temporal Engine...");
    scheduler::run_lookahead_loop(
        dummy_timeline, 
        link_state, 
        superdirt_socket, 
        chuck_socket
    ).await?;

    Ok(())
}
